branch-defaults:
  master:
    environment: listmkr-dev
    group_suffix: null
global:
  application_name: listmkr
  branch: null
  default_ec2_keyname: listmkr
  default_platform: Docker 1.7.1
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
